import { SolanaProvider } from "@/components/solana/solana-provider";
import "@mantine/core/styles.css";
import { ReactQueryProvider } from "../components/global/react-query-provider";
import "./globals.css";

import { theme } from "@/config/mantine";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Placeholder",
  description: "Generated by create-solana-dapp",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className} {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ReactQueryProvider>
          <SolanaProvider>
            <body>
              <MantineProvider theme={theme} forceColorScheme="dark">
                {children}
              </MantineProvider>
            </body>
          </SolanaProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
