import MainLayout from "@/components/layouts/MainLayout";
import { SolanaProvider } from "@/components/solana/SolanaProvider";
import { theme } from "@/config/mantine";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import "@mantine/core/styles.css";
import { Roboto } from "next/font/google";
import ReactQueryProvider from "../components/global/ReactQueryProvider";

import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Placeholder",
  description: "Generated by create-solana-dapp",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className} {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <ReactQueryProvider>
          <SolanaProvider>
            <body>
              <MantineProvider
                theme={theme}
                defaultColorScheme="dark"
                forceColorScheme="dark"
              >
                <MainLayout>{children}</MainLayout>
              </MantineProvider>
            </body>
          </SolanaProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
